# Generated by Django 4.2.2 on 2023-07-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
